### ISSUE TITLE
Add or replace scss

### ISSUE THREAD

**Issue by merijnponzo** [barthy-koeln/scroll-snap-slider#10]
Is it possible to add or replace the .scss file?
Than i can import the .css file to my tailwind.css, with post css, very common nowadays.

Or add them both, just add your outputted .css file to the src folder (without minifying it)

thanks

**Comment by barthy-koeln** [comment]
Agreed, this could be useful. I will think of something and contact you ASAP 👍🏼

**Comment by barthy-koeln** [comment]
Hey @merijnponzo :)

If you like, could you check out the changes in `feature/plugins` branch?

I moved the styles to CSS and kept the SCSS file for backward compatibility.
Does that work for you?

**Comment by merijnponzo** [comment]
Super, looking forward to import into my tailwind.css !

**Comment by merijnponzo** [comment]
Tip, if I use an unested .scroll-snap-slide within scroll-snap-slider.css
```
.scroll-snap-slide {
```
instead of 
```
.scroll-snap-slider .scroll-snap-slide { 
```

I can easily overrule .scrolls-snap-slide with my tailwind props
```
<div class="scroll-snap-slider cardslider">
   <div class="scroll-snap-slide w-screen h-full bg-one ds:w-1/3">
```
(ds: is my desktop breakpoint prefix)

So for example, I use a (non scrollable) 3 column layout on desktop, and scrollable columns on mobile I add

```
@screen ds {
  .cardslider{
    .overflow-x: hidden;
  }
}
```
to my cardslider in my tailwind app.css

Best

**Comment by barthy-koeln** [comment]
I guess there's no harm in that. `.scroll-snap-slide` has a specific enough name to not conflict with anything else (I think).

I updated it.
