### ISSUE TITLE
Integrating scroll-snap-api for current slide and revamp the setup

### ISSUE THREAD

**Issue by merijnponzo** [barthy-koeln/scroll-snap-slider#14]
Hi,

Like i mentioned in the draggable issue, maybe the scroll-snap-api can help to get a more accurate result on your current slide. 
I wrote a proof a concept below, which also works with scroll-snap-align: start; And vertical scrolls could be easily added.

There's no debouncer in the scroll, and it isn't clean code but here's an idea for a revamp

```
 // init slider
  Slider.init({
    slider: ".snap-slider",
    item: ".snap-slide",
    active:".active",
    // can be false or ignored
    paginate: ".snap-paginate", 
    mousedrag:true,
    autoplay:false,
  });
 ```

- This means that multiple sliders can be activated at once, no plugins (that extra 4kb is worth it for a faster setup)
- You could add a default css file with default classnames as well, but you can also use your own classnames
- an active class would be very helpfull, assigned to the slides and buttons (not yet in this example)
- slider should be re-iniated on resizing the window since the coordinates of the scroll-snap-api needs to be calculated again

there is also an next and prev within the scroll-snap-api
```
import { scrollSnapToNext } from 'scroll-snap-api';
scrollSnapToNext( scrollingElement, 'right' ); // 'left', 'right', 'up', 'down'
```

structure
```
<section>
 <div class="snap-slider w-480">
      <article class="snap-slide">
       <h4>Slide 1</h4>
      </article>
       <article class="snap-slide">
       <h4>Slide 2</h4>
      </article>
    </div>
    <!-- paginate should be at the same level as the snap container
    <div class="snap-paginate">
        <button>1</button>
       <button>2</button>
    </div>
 </section>
```

css
```
.snap-slider {
  display: flex;
  flex-wrap: nowrap;
  justify-content: normal;
  -ms-overflow-style: none; /* IE and Edge */
  overflow-x: auto;
  scroll-behavior: smooth;
  scroll-snap-type: x mandatory;
  scroll-snap-stop: always;
  scrollbar-width: none; /* Firefox */
}

.snap-slider::-webkit-scrollbar {
  display: none;
}

.snap-slide {
  align-items: center;
  display: flex;
  flex: 0 0 auto;
  flex-direction: column;
  justify-content: center;
  max-width: none;
  scroll-snap-align: start;
  width: 100%;
}
```

javscript.

```
import { getScrollSnapPositions, getSnapPositions } from "scroll-snap-api";

const Slider = {
  init(setup) {
    let lastScrollTop = 0;
    const snapSliders = document.querySelectorAll(setup.slider);
    // activate sliders
    for (let i = 0; i < snapSliders.length; i++) {
      const snapSlider = snapSliders[i];
      const snapSlides = snapSlider.querySelectorAll(setup.item);
      // set active slide
      snapSlider.currentSlide = 0;

      if (snapSlider) {
        const snapPositions = getScrollSnapPositions(snapSlider);
        //  const snapPositionsRaw = getScrollSnapPositions(snapSlider);
        // set scrollListener
        snapSlider.addEventListener(
          "scroll",
          function () {
            const x_index = getSnapX(this.scrollLeft, snapPositions);
            // console.log(this.scrollLeft);
            changeSlide(x_index, snapSlides);
          },
          false
        );
        // get paginate (should be below or above the .snap-slider)
        const snapPaginate = snapSlider.parentElement.querySelector(
          setup.paginate
        );

        // set buttons
        if (snapPaginate) {
          const buttons = snapPaginate.children;
          for (let b = 0; b < buttons.length; b++) {
            buttons[b].onclick = function (event) {
              // scrollTo
              let scrollPositionX = 0;
              if (b === buttons.length - 1) {
                scrollPositionX = snapSlider.scrollWidth;
              } else {
                scrollPositionX = snapPositions.x[b];
              }
              snapSlider.scrollTo({
                left: scrollPositionX,
              });
            };
          }
        }
      }
      // correction of snap indent of last slide
      function snapIndentX(snapPositions) {
        let snapIndent = 0;
        if (snapPositions) {
          snapIndent =
            snapPositions.x[snapPositions.x.length - 1] - snapPositions.x[0];
            // last slide x position - first slide x position 
        }
        return snapIndent;
      }
      // returns the current horizontal slide
      function getSnapX(scrollX, snapPositions) {
        // check curentSlide
        for (const s in snapPositions.x) {
          const snap = snapPositions.x[s];
          if (snap === scrollX || snap === snapIndentX(snapPositions)) {
            return s;
          }
        }
      }
      // getSlide and adds active class to it
      function changeSlide(index, curSnapSlides) {
        curSnapSlides.forEach(function (el) {
          el.classList.remove(setup.active);
        });
        const slide = curSnapSlides[index];
        if (slide) {
          slide.classList.add(setup.active);
        }
      }
    }
  },
};
export default Slider;
```

This is just an idea, don't feel obligated to use the scroll-snap-api, but I like the idea of less setup and the scroll-snap-api which handles lots of complex measurements

**Comment by merijnponzo** [comment]
> Hi,
> 
> Like i mentioned in the draggable issue, maybe the scroll-snap-api can help to get a more accurate result on your current slide. I wrote a proof a concept below, which also works with scroll-snap-align: start; And vertical scrolls could be easily added.
> 
> There's no debouncer in the scroll, and it isn't clean code but here's an idea for a revamp
> 
> ```
>  // init slider
>   Slider.init({
>     slider: ".snap-slider",
>     item: ".snap-slide",
>     active:".active",
>     // can be false or ignored
>     paginate: ".snap-paginate", 
>     mousedrag:true,
>     autoplay:false,
>   });
> ```
> 
>     * This means that multiple sliders can be activated at once, no plugins (that extra 4kb is worth it for a faster setup)
> 
>     * You could add a default css file with default classnames as well, but you can also use your own classnames
> 
>     * an active class would be very helpfull, assigned to the slides and buttons (not yet in this example)
> 
> 
> structure
> 
> ```
> <section>
>  <div class="snap-slider w-480">
>       <article class="snap-slide">
>        <h4>Slide 1</h4>
>       </article>
>        <article class="snap-slide">
>        <h4>Slide 2</h4>
>       </article>
>     </div>
>     <!-- paginate should be at the same level as the snap container
>     <div class="snap-paginate">
>         <button>1</button>
>        <button>2</button>
>     </div>
>  </section>
> ```
> 
> css
> 
> ```
> .snap-slider {
>   display: flex;
>   flex-wrap: nowrap;
>   justify-content: normal;
>   -ms-overflow-style: none; /* IE and Edge */
>   overflow-x: auto;
>   scroll-behavior: smooth;
>   scroll-snap-type: x mandatory;
>   scroll-snap-stop: always;
>   scrollbar-width: none; /* Firefox */
> }
> 
> .snap-slider::-webkit-scrollbar {
>   display: none;
> }
> 
> .snap-slide {
>   align-items: center;
>   display: flex;
>   flex: 0 0 auto;
>   flex-direction: column;
>   justify-content: center;
>   max-width: none;
>   scroll-snap-align: start;
>   width: 100%;
> }
> ```
> 
> javscript.
> 
> ```
> import { getScrollSnapPositions, getSnapPositions } from "scroll-snap-api";
> 
> const Slider = {
>   init(setup) {
>     let lastScrollTop = 0;
>     const snapSliders = document.querySelectorAll(setup.slider);
>     // activate sliders
>     for (let i = 0; i < snapSliders.length; i++) {
>       const snapSlider = snapSliders[i];
>       const snapSlides = snapSlider.querySelectorAll(setup.item);
>       // set active slide
>       snapSlider.currentSlide = 0;
> 
>       if (snapSlider) {
>         const snapPositions = getScrollSnapPositions(snapSlider);
>         //  const snapPositionsRaw = getScrollSnapPositions(snapSlider);
>         // set scrollListener
>         snapSlider.addEventListener(
>           "scroll",
>           function () {
>             const x_index = getSnapX(this.scrollLeft, snapPositions);
>             // console.log(this.scrollLeft);
>             changeSlide(x_index, snapSlides);
>           },
>           false
>         );
>         // get paginate (should be below or above the .snap-slider)
>         const snapPaginate = snapSlider.parentElement.querySelector(
>           setup.paginate
>         );
> 
>         // set buttons
>         if (snapPaginate) {
>           const buttons = snapPaginate.children;
>           for (let b = 0; b < buttons.length; b++) {
>             buttons[b].onclick = function (event) {
>               // scrollTo
>               let scrollPositionX = 0;
>               if (b === buttons.length - 1) {
>                 scrollPositionX = snapSlider.scrollWidth;
>               } else {
>                 scrollPositionX = snapPositions.x[b];
>               }
>               snapSlider.scrollTo({
>                 left: scrollPositionX,
>               });
>             };
>           }
>         }
>       }
>       // correction of snap indent of last slide
>       function snapIndentX(snapPositions) {
>         let snapIndent = 0;
>         if (snapPositions) {
>           snapIndent =
>             snapPositions.x[snapPositions.x.length - 1] - snapPositions.x[0];
>             // last slide x position - first slide x position 
>         }
>         return snapIndent;
>       }
>       // returns the current horizontal slide
>       function getSnapX(scrollX, snapPositions) {
>         // check curentSlide
>         for (const s in snapPositions.x) {
>           const snap = snapPositions.x[s];
>           if (snap === scrollX || snap === snapIndentX(snapPositions)) {
>             return s;
>           }
>         }
>       }
>       // getSlide and adds active class to it
>       function changeSlide(index, curSnapSlides) {
>         curSnapSlides.forEach(function (el) {
>           el.classList.remove(setup.active);
>         });
>         const slide = curSnapSlides[index];
>         if (slide) {
>           slide.classList.add(setup.active);
>         }
>       }
>     }
>   },
> };
> export default Slider;
> ```

**Comment by barthy-koeln** [comment]
Thank you for taking the time to write all of this down. Again, I'm sorry for the delay. The end of the year is always very chaotic, and I finally had two weeks off — I had forgotten what that is like.

Anyway, there are a few points I want to address:

 ## scroll-snap-api

I will look into [scroll-snap-api](https://github.com/LachlanArthur/scroll-snap-api) and see if we can easily improve precision and capability. I'm sure

## Pagination

In my experience, it's not always as easy as "paginate should be at the same level as the snap container". The designers I work with have different Ideas, and it's my job to make their visions come true.
Which is why I'm a fan of plugins and easy replacements. If the pagination feature doesn't suit you, just don't import it.

In contrast to that, I've had to override and monkey patch open-source libraries several times because features that should have been customizable or extendable were part of the core library.

## Initializing multiple sliders at once

This I'm avidly against. An instance of a component called `ScrollSnapSlider` should represent exactly 1 slider.
I could potentially agree with a static method that returns an array of instances, but then again, it's just a for-loop that is probably better done in your own project.

**Comment by barthy-koeln** [comment]
Hello @merijnponzo :)

I've kept this task open to see if anything would come up on my side that would justify a rewrite or more in-depth calculations like the scroll-snap-api does.

Nothing came up so far. I will close this issue now since I prefer having a more specific but small than general and big library.
As stated in the README:

> This library is a shortcut to something I personally have to implement in almost every website.

Thanks for your understanding!

Barthy
