### ISSUE TITLE
Not responsive in Safari and Firefox?

### ISSUE THREAD

**Issue by hrdlnk** [barthy-koeln/scroll-snap-slider#17]
Much thanks for this nice project!
It seems it’s not responsive in Safari or Firefox (tested under macOS 11.7)

- **Safari**
   Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/605.1.15 (KHTML, like Gecko) Version/16.0 Safari/605.1.15
- **Firefox**
   Mozilla/5.0 (Macintosh; Intel Mac OS X 10.15; rv:105.0) Gecko/20100101 Firefox/105.0

**Comment by barthy-koeln** [comment]
Hey, I can test Safari later today. Firefox looks good on my end.

Your user agent strings say `Mac OS X 10.15` (Catalina), but at the top you wrote `macOS 11.7` (Big Sur). Which one is it?

Please include some code, a link, or screenshots. I need to see or reproduce the problem.

**Comment by barthy-koeln** [comment]
Closing this as there hasn't been an answer in a week.
