### ISSUE TITLE
Prevent quirky slide on mouse drag quick swipe distance

### ISSUE THREAD

**Issue by oncode** [barthy-koeln/scroll-snap-slider#19]
Thank you for the awesome library! I'm currently doing a WebComponent implementation of the slider and noticed when I'm using mouse drag with a small drag distance, the slide scrolls smoothly in the beginning, but then abruptly goes to the end. You can see it on the demo page if you look closely or increase the slider width.

This happens when the smooth scrolling has not finished before the 300ms timeout, which reenables the scroll-snap and snaps it directly in to place.

I then replaced the timeout code:
```
this.disableTimeout = window.setTimeout(() => {
  this.scrollElement.style.scrollSnapStop = null;
  this.scrollElement.style.scrollSnapType = null;
}, 300)
```

With setting a flag whether the dragging has just stopped and only if it has, I reenable the scroll-snap on the next slide-stop:
```
private startDragging = (event) => {
  this.stoppedDragging = false;
  // ...
}

private stopDragging = (event) => {
  // ...
  this.stoppedDragging = true;
}

this.slider.addEventListener('slide-stop', () => {
    if (this.stoppedDragging) {
      this.stoppedDragging = false;
      this.scrollElement.style.scrollSnapStop = null;
      this.scrollElement.style.scrollSnapType = null;
    }
});
```

Now the slide scrolls smoothly to the end even with the short mouse drag distance. I thought you maybe want adopt this too into the library.

**Comment by barthy-koeln** [comment]
Hi again, 

There are new commits in the `typescript` branch that hopefully resolve this issue.
I check if the slider is at the far-left or far right and re-enable scroll-snapping manually if it is.

If not, I add a “once” listener for the next `slide-stop`.

**Comment by oncode** [comment]
Seems to be working good :)
