### ISSUE TITLE
Pause autoplay when user is scrolling

### ISSUE THREAD

**Issue by oncode** [barthy-koeln/scroll-snap-slider#20]
Autoplay currently only stops when a user is dragging with the mouse, but should probably stop too when the user is scrolling with the trackpad or touch device. In this way the user drag is not interrupted by the autoplay.

```
this.slider.addEventListener('slide-start', () => {
    const autoplay = this.slider.plugins.get('ScrollSnapAutoplay')
    if (autoplay) {
      autoplay.disable()
    }
});

this.slider.addEventListener('slide-stop', () => {
    const autoplay = this.slider.plugins.get('ScrollSnapAutoplay')
    if (autoplay) {
      autoplay.enable()
    }
});
```

Maybe it would also be a good idea to add an option to stop autoplay on mouseover. So users can interact with content inside the slide without being interrupted by autoplay.

**Comment by barthy-koeln** [comment]
Hi Manuel, thank you for your interest.

I'm currently working on a TypeScript branch and have included a [feature in the `ScrollSnapAutoplay` plugin](https://github.com/barthy-koeln/scroll-snap-slider/blob/fe6c4e1ca24f449505bb620960778aa29d6e5af3/src/ScrollSnapAutoplay.ts#L40):

```js
this.slider.addEventListener('touchstart', this.disableTemporarily, { passive: true })
this.slider.addEventListener('wheel', this.disableTemporarily, { passive: true })
```

By default, it will pause for a certain time after `touchstart` and on `wheel` events. You can listen to other events as well and use the `disableTemporarily` method to do your thing.

The `typescript` branch contains transpiles JS in he `build` folder.
Does that work for you?

If you test and report back, it'll speed up the testing phase and lead to a quicker stable release :)

**Comment by barthy-koeln** [comment]
I just now realized that the `touchstart` might be better changed to `touchmove` to prevent autoplay while the user is still dragging.

The `wheel` event already is triggered as long as the user “wheels” with a mouse or trackpad.

___

Regarding this:

> stop autoplay on mouseover

I would consider this a special case that is easily achievable with the plugin's API and listening for `pointermove` events, but not a core slider feature.

**Comment by oncode** [comment]
That's a good alternative with the `wheel` and `touchmove` event. 
Then I will add the stop on `mouseover` and `focusin` manually. Thank you for the fast feedback!

**Comment by barthy-koeln** [comment]
Hi again, I've released the new version to npm.

Any further feedback is still welcome :)
