### ISSUE TITLE
How to pause and resume autoplay

### ISSUE THREAD

**Issue by felixranesberger** [barthy-koeln/scroll-snap-slider#29]
I would like to pause the autoplay using my own pause and play button implementation. 
I found two functions in the autoplay plugin that seemed to enable this behaviour: `disable` and `disable`.
When executing the functions nothing happens.

This is my current code:

```ts
const autoplayPluginInstance = new ScrollSnapAutoplay(5000);

const sliderInstance = new ScrollSnapSlider({ element }).with([
  new ScrollSnapDraggable(),
  autoplayPluginInstance,
  new ScrollSnapLoop(),
]);

pauseButton.addEventListener('click', () => {
  autoplayPluginInstance.disable(); // does not work
  autoplayPluginInstance.disableTemporarily(); // does also not work
});

playButton.addEventListener('click', () => {
  autoplayPluginInstance.enable();
});
```

How can I pause and resume the autoplay correctly?

**Comment by barthy-koeln** [comment]
Using `enable()` and `disable()` and `disableTemporarily()` definitely works locally and in [this demo](https://codepen.io/barthy-koeln/pen/gbYMpvx).

Can you provide a reproduction using stackblitz, codepen, or just a full code snippet?
You can fork the codepen above.

One reason I can think of would be this:
* The plugin starts as enabled, unless you use `.with([autoplay], false)`
* If you call `.enable()` on an already enabled plugin, you'll end up with multiple intervals
* When you then call `.disable()`only the newest interval will be removed and pending intervals will continue to execute.

I'm thinking of calling the `disable` function at the start of the `enable` function to remedy that.

**Comment by felixranesberger** [comment]
I think I just realized what my issue was.
I'm using a signals pattern with a `isSliderPlaying` reactive variable to toggle the slider on and off. 
This also adjusts my play and pause buttons to have the correct visibility and some other things. 
Calling the `isSliderPlacing.effect(() => {})` will execute it once initially and thus creating multiple intervals. 

My pull request [here](https://github.com/barthy-koeln/scroll-snap-slider/pull/34) would also probably fix the issue, since the `timer.start()` function only allows a single interval at a time.

**Comment by barthy-koeln** [comment]
Your pull request would resolve the issue, but my suggested change affects a single line: #35

Can you test you code with the `fix/cleanup-autoplay` branch?

**Comment by felixranesberger** [comment]
Sure thing, but how do can I test it? 
I would install the GitHub branch, but the `dist` folder isn't updated with your code change.

**Comment by barthy-koeln** [comment]
I pushed the updated dist folder now :)

**Comment by felixranesberger** [comment]
Just tried it out, works now :)
