### ISSUE TITLE
Changing slide does not reset autoplay interval

### ISSUE THREAD

**Issue by felixranesberger** [barthy-koeln/scroll-snap-slider#30]
When I navigate to the next slide using a custom control panel and the `slideTo(index)` function, I would assume that the autoplay interval gets reset. Otherwise you can scroll through the slides using arrow buttons and the slider changes unexpected due to a new autoslide.

**Comment by barthy-koeln** [comment]
Hi Felix,

Thanks for your interest and all this feedback. I'll find the time to look into it as soon as I get the chance, possibly on my next train ride.

**Comment by barthy-koeln** [comment]
> When I navigate to the next slide using a custom control panel [...] I would assume that the autoplay interval gets reset
Yes, absolutely, but not every call to `slideTo` will be triggered by user-input.

I've intentionally left this out of the `slideTo` function, enabling programmatic calls to `slideTo` that do not require pausing.

Luckily, it's straightforward to use the `autoplay.disableTemporarily()` method whenever your users interact.
Take a look at the [demo code](https://github.com/barthy-koeln/scroll-snap-slider/blob/e183773363de4251e7f1c7b2a1d0793c062a674c/demo/slider-simple.js#L51) if you like.

Now combined with issue #29 I think you should be able to easily achieve what you want. If not, let me know.

**Comment by felixranesberger** [comment]
This works, thanks for the tip!
