### ISSUE TITLE
some additional improvements and features

### ISSUE THREAD

**Issue by onlinebizsoft** [barthy-koeln/scroll-snap-slider#8]
I have tested and compared this with some other available scroll snap implementation for sliders and this is the best so far. Thank you very much

I have a few features which it would be great to includes in this
1. Infinity Loop
2. Lazy load
I'm not sure if this is going to work with https://github.com/aFarkas/lazysizes itself so when the page loading, any slider images which are not in viewport will be holding until they get scrolled and get in viewport?
Otherwise the slider itself should support a lazy load function
3. Auto play

**Comment by barthy-koeln** [comment]
Hello and thank you!

My answers to all three points boil down to the same statement: I try to keep this library as minuscule as possible, in a way that it covers 80% of my needs for all projects. The remaining 20% are always project-specific and can be implemented in few lines per project.

But I agree that it would be helpful to provide examples for these three features you mentioned, as they are quite common.

Some quick examples (also added to the [demo](https://codepen.io/BarthyB/pen/JjXgzOL)):

1) Infinite Loop:
```js
const sliderElement = document.querySelector(".example-slider")
const slider = new ScrollSnapSlider(sliderElement);
const slides = sliderElement.getElementsByClassName('scroll-snap-slide')
slider.addEventListener("slide-stop", function () {
  const lastIndex = slides.length - 1
  
  if(slider.slide === 0){
    sliderElement.prepend(slides[lastIndex])
    return
  }
  
  if(slider.slide === lastIndex){
    sliderElement.append(slides[0])
  }
});
```

2) Lazy load

```js
slider.addEventListener("slide-stop", function (event) {
  // load neighbouring slides from index at event.detail
});
```

3) Autoplay:

```js
const slides = document.querySelectorAll('.scroll-snap-slide')
window.setInterval(function() {
  const target = slider.slide < slides.length - 1 ? slider.slide + 1 : 0
  slider.slideTo(target)
}, 3141)
```

**Comment by barthy-koeln** [comment]
Hey  @onlinebizsoft !

I have just pushed some changes into `main`.

Since the looping and autoplay requirements have shown up at multiple occasions now, I wanted to include them directly in this library.

I have created plugins, which you can enable and combine at will.

Check out the new demo: https://barthy-koeln.github.io/scroll-snap-slider/

I'll release a new version this weekend and I consider this issue as closed now.
Thanks again for your interest :)

**Comment by onlinebizsoft** [comment]
@barthy-koeln I cant see loop one on the demo?
