### ISSUE TITLE
Make it draggable as well?

### ISSUE THREAD

**Issue by merijnponzo** [barthy-koeln/scroll-snap-slider#9]
Awesome plugin, I wrote something like this myself but it was very difficult to create listeners on the 'snapped' area's.

Would it be an idea to add a drag functionality (at least for desktop) to the carousels?
I found this:
https://codepen.io/fredericrous/pen/xxVXJYX

I often catch myself dragging on scrollsnap containers- since most carousels like swiper or flickity only work with drag for desktop. But i also swipe with my touchpad on my macbook, so supporting both would be awesome.

**Comment by barthy-koeln** [comment]
I will add it to the collection of examples soon, using the HTML5 drag
feature.

I don't think it should be a core feature, as you might want to use any
different dragging library.

But again, I'll contact you ASAP.

**Comment by barthy-koeln** [comment]
Hello again @merijnponzo !

Check out the new demo: https://barthy-koeln.github.io/scroll-snap-slider/

The code and documentation are currently in `main` and are considered release candidates.
I'll release a new version this weekend, but I'll wait for your feedback if you have any.

**Comment by merijnponzo** [comment]
Hello Barthy that is just  awesome, I will check it out in a production site soon and let you know what happens!

**Comment by merijnponzo** [comment]
I can confirm it works, awesome!
For wide sliders I need to drag the current slide across the center (horizontal half) to move on to the next.

Maybe i can adjust this with either one of these options, but i didn't test that yet
```
slider.scrollTimeout = 50 // Sets a shorter tiemout to detect scroll end
slider.roundingMethod = Math.ceil 
```

Also, importing the plugins within any other app will be
```
import { ScrollSnapDraggable } from "scroll-snap-slider/src/ScrollSnapDraggable.js";
``
instead of 
```
import { ScrollSnapLoop } from '../src/ScrollSnapLoop.js'
```
Am I right?
Something to mention in your documentation

Super

**Comment by barthy-koeln** [comment]
Hi, thanks for the feedback.

I fixed the imports in the README, that was just a copy+paste mistake.

> drag the current slide across the center

The `slider.roundingMethod` should be able to change this behaviour to some extent, although I currently don't know how to achieve what you describe.

You might want to code your own method:

```js
/**
 * @param {Number} x the current slide position as a decimal (e.g. 1,5 = slide at index 1 has been slided by 50%)
 */
slider.roundingMethod = function(x) {
  // TODO return an integer that will be the the slider.slide
  return Math.round(x)
}
```

**Comment by merijnponzo** [comment]
I dont see how slider.roundingMethod would solve this problem but maybe you can explain further

The problem is that if you enable the draggablePlugin and you use for example 'cards' half of your viewport- you have to drag ridiculously hard to get it moving, and the last card is never reached

![slider](https://user-images.githubusercontent.com/23075300/143880346-004159a6-9e11-4d3e-950a-d4a026dcea11.gif)


My suggestion would be to check for the drag direction (left or right, top or down) and then add or subtract your slide index.

The example below already navigates to the right slides, responding to a short drag left or right.
A nice extra touch would be to add add the this.element.scrollLeft += distance; from your plugin to get a visual respond to your mouse dragging.


```
import { ScrollSnapSlider } from "scroll-snap-slider";

const Slider = {
  init() {
    // init scrollable section
    let isDragging = false;
    let startX = 0;
    let currentX = 0;

    const sliders = document.querySelectorAll(".scroll-snap-slider");
    for (let i = 0; i < sliders.length; i++) {
      const SliderElement = sliders[i];

      if (SliderElement) {
        // the slider
        const slider = new ScrollSnapSlider(SliderElement, true, []);
        const prev = SliderElement.querySelector(".scroll-snap-prev");
        const next = SliderElement.querySelector(".scroll-snap-next");
        // add pagination
        if (prev) {
          prev.addEventListener("click", function () {
            slider.slideTo(slider.slide - 1);
          });
        }
        if (next) {
          next.addEventListener("click", function () {
            slider.slideTo(slider.slide + 1);
          });
        }
        slider.addEventListener("mousedown", (e) => {
          startX = e.offsetX;
          currentX = 0;
          isDragging = true;
          // 
          if (e.stopPropagation) e.stopPropagation();
          if (e.preventDefault) e.preventDefault();
          e.cancelBubble = true;
          e.returnValue = false;
        });
        slider.addEventListener("mousemove", (e) => {
          if (isDragging === true) {
            currentX = e.offsetX;
          }
        });
        slider.addEventListener("mouseup", (e) => {
          if (isDragging === true) {
            let currentSlide = slider.slide;
            if (startX > currentX) {
              currentSlide++;
            } else if (startX < currentX) {
              currentSlide--;
            }
            setTimeout(function () {
              slider.slideTo(currentSlide);
              slider.slide = currentSlide;
            }, 1000);

            isDragging = false;
          }
        });
      }
    }
  },
};
export default Slider;
```

**Comment by barthy-koeln** [comment]
Can you have a look if #13 does what you want?
